### ISSUE TITLE
The Playground needs better styling [CSS]

### ISSUE THREAD

**Issue by aantron** [aantron/dream#105]

**Comment by tcoopman** [comment]
What do you want to change?

**Comment by thangngoc89** [comment]
What are you thinking about? I know some CSS

**Comment by aantron** [comment]
In general, the CSS is a bit ugly and not polished. I think the overall layout is pretty much right (including collapsing down on thin viewscreens). But it just doesn't have that polished, legible feel of nice, thought-out spacing, etc. In addition, if colors could be made better, it would be nice to see how :)

**Comment by thangngoc89** [comment]
I didn't notice until you said it. The padding and spacing are a little bit off. I don't write pure css these days but let's me see what I can do.

**Comment by aantron** [comment]
@thangngoc89 in https://github.com/aantron/dream/pull/109#issuecomment-874299534:

> I think we would need to design this in a design program to see how things go. It's easier to move things around by drag and drop then write css code.

Probably also a good idea :)

**Comment by aantron** [comment]
A relatively good way to develop the playground is to save the HTML and/or JS locally, and then run it. Maybe I should put some effort into making the playground more easily deployable/runnable locally.

**Comment by aantron** [comment]
Closing this for now, after several improvements by @thangngoc89 and @artileda.

More improvements are still welcome, however, if you spot anything. Or just think the Playground looks ugly :)
