### ISSUE TITLE
Test on intermediate compiler versions between 4.08 and 4.12

### ISSUE THREAD

**Issue by aantron** [aantron/dream#121]
Due to #117.

**Comment by aantron** [comment]
Can be done by adding more entries here:

https://github.com/aantron/dream/blob/8612f6a661053ba4e0800c9c6c7f39bdefd5f9eb/.github/workflows/test.yml#L17-L19

**Comment by thangngoc89** [comment]
I don't see that you're using any cache in CI. This would make it super slow . 
Can we cache `/.opam` folder across builds?

**Comment by aantron** [comment]
> Can we cache `/.opam` folder across builds?

I think with `setup-ocaml` v2 it's doable. I haven't tried recently, and caching didn't seem to be working on v1. Caching is definitely useful &mdash; most of my earlier Travis-using projects had caching that made builds take ~30 sec.

The Dream build in CI currently takes [10 minutes on Linux and 20 minutes on macOS](https://github.com/aantron/dream/runs/3022534408?check_suite_focus=true), which is bad, but not yet awful.

**Comment by aantron** [comment]
GHA runs all the builds in parallel, so adding more rows did not affect the overall build time.
