### ISSUE TITLE
Add drop_cookie helper

### ISSUE THREAD

**Issue by aantron** [aantron/dream#144]
```ocaml
Dream.drop_cookie name request response =
  Dream.set_cookie name "" request response ~expires:0. ~encrypt:false
```

`Dream.drop_cookie` should have all the same optionals as [`Dream.set_cookie`](https://aantron.github.io/dream/#val-set_cookie), and simply forward them, except that it shouldn't have `~expires`, `~max_age`, or `~encrypt` at all. It can be added right after `set_sookie`:

https://github.com/aantron/dream/blob/ead188384b89322455eb6a6c69541a9ece48e34b/src/pure/inmost.ml#L647

**Comment by Patil2099** [comment]
I would love to take this up

**Comment by sagarjs** [comment]
Looks like this has not moved since two months; can I pick this up?

**Comment by aantron** [comment]
Yes, please!

**Comment by sagarjs** [comment]
Would the optional parameters like prefix have to be checked and forwarded to set_cookie?

**Comment by aantron** [comment]
@sagarjs I believe they would just have to be forwarded to `set_cookie`, since that function already knows what to do with them. That guarantees that the same cookie is being "targeted" by `drop_cookie` as would be targeted by `set_cookie`.
