### ISSUE TITLE
missing multipart_form dependency 

### ISSUE THREAD

**Issue by joprice** [aantron/dream#197]
I'm building the master branch and hitting an error when trying to resolve multipart_form.lwt. It looks like 0.4.0 of multipart_form split it out into another dependency. Maybe the bounds on multipart form (`"multipart_form" {>= "0.3.0"}` ) need to be adjusted to avoid allowing it to pull in that version? 

```
# 14 |   multipart_form.lwt
#        ^^^^^^^^^^^^^^^^^^
# Error: Library "multipart_form.lwt" not found.
```

**Comment by aantron** [comment]
Based on [this commit](https://github.com/ocaml/opam-repository/pull/20565/commits/2dbcf46a183e3f9b2576512ef4685720499fc750) added to opam just recently, I think it should be `>= "0.3.0" & < "0.4.0"`. I will confirm later today and update this repo. Thanks for the report!

**Comment by aantron** [comment]
(Or, even better, Dream should be updated to use and require 0.4.0, as part of #193)

**Comment by aantron** [comment]
Should be fixed now. Thanks again!
