### ISSUE TITLE
Add `?trim:bool` param to `Dream.query`?

### ISSUE THREAD

**Issue by yawaramin** [aantron/dream#204]
Or perhaps even just trim the values automatically?

E.g. some clients might send queries like `?q=` (with no value) or `?q= ` (single space character as the value).

In these cases perhaps we should evaluate to `None` for `Dream.query ~trim:true req "q"`?

**Comment by aantron** [comment]
Would you be willing to make a PR for this, calling the option `?filter_empty`?

**Comment by tatchi** [comment]
@yawaramin did you start working on that one? I haven't checked the code yet but that looks like something that _shouldn't_ be too difficult to implement so I would be happy to try :)

**Comment by yawaramin** [comment]
@tatchi I had not, got distracted by other things 😅 Please feel free!

**Comment by aantron** [comment]
@yawaramin what was the original context for this? What client was sending `?q=` or `?q= `, and in what circumstance? Is there some kind of inconsistency between clients in this behavior?

**Comment by aantron** [comment]
I'm going to close this as something very specific to a certain use case (which may not exist) and easily implementable by Dream's users when needed.

**Comment by yawaramin** [comment]
Now with typed form decoding/validation in [dream-html](https://yawaramin.github.io/dream-html/dream-html/Dream_html/Form/index.html), we will be able to use the same functionality for decoding queries into typed values and enforcing constraints like 'must be nonempty'. Obviously for the simple case above it's overkill, but just for demonstration purposes:

```ocaml
open Dream_html.Form

let nonempty = ensure "error.expected.nonempty" (( <> ) "") required string

let handler request =
  let q = validate (nonempty "q") (Dream.all_queries request) in
  ...
```

**Comment by aantron** [comment]
Looks neat!
