### ISSUE TITLE
Dream.run ~secret is documented but does not exist

### ISSUE THREAD

**Issue by tjltjl** [aantron/dream#207]
dream.mli in comment: 

"Specify {!Dream.run} argument [~secret], or the Web app will not be able to
    decrypt cookies from prior starts."

(also documented on the website)

However, the actual signature of Dream.run is different:

val run :
  ?interface:string ->
  ?port:int ->
  ?stop:unit promise ->
  ?error_handler:error_handler ->
  ?tls:bool ->
  ?certificate_file:string ->
  ?key_file:string ->
  ?builtins:bool ->
  ?greeting:bool ->
  ?adjust_terminal:bool ->
    handler -> unit

**Comment by aantron** [comment]
Indeed, you should use `Dream.set_secret`. I did not catch all occurrences of `~secret` when updating the docs. I'll fix that in a commit later today. Thank you very much for pointing this out!
