### ISSUE TITLE
`Stream` module no longer available in OCaml 5

### ISSUE THREAD

**Issue by patricoferris** [aantron/dream#208]
Hi :)) Thanks for the great library! 

I'm doing some work with OCaml 5 and since https://github.com/ocaml/ocaml/pull/10896 the `Stream` library now needs to be explicitly pulled in via https://github.com/ocaml/camlp-streams (which I did quickly https://github.com/patricoferris/dream/commit/21e981fdc500f8728e984faaf1fef9bff0d26cfe) but I wasn't sure if this is the approach you wanted to go for (maybe vendoring your own `Stream` for `eml` or something like that?).

Anyway just thought I'd report it as I couldn't see any other issues/PRs open for it.

**Comment by aantron** [comment]
Thanks :)

I'd be happy to merge that diff as part of a PR!
