### ISSUE TITLE
`include` equivalent in eml?

### ISSUE THREAD

**Issue by yomimono** [aantron/dream#215]
I'm sure I'm missing something basic, but I couldn't figure out a better way to include bits of `eml` templating in later bits than this:

```
let a =
<p>arglebargle</p>

let b =
<html><body>
%  Buffer.add_string ___eml_buffer a;
</body></html>
```

which definitely doesn't feel like the Right Thing. Is there a nicer way to include previously defined fragments in eml?

**Comment by aantron** [comment]
You should be able to use `<%s! a %>` to include `a` verbatim as an unescaped string.
