### ISSUE TITLE
Not able to load images in html

### ISSUE THREAD

**Issue by OscarLahaie** [aantron/dream#226]
Hello, it is my first time using dream and I encounter a bug that I can't fix. My image won't load on the HTML page however I can access them directly with their address. Any idea why images are not loading?

Expected result :
![image](https://user-images.githubusercontent.com/25438086/172014422-a3e2a4b0-0aa1-4e3d-86bf-5bb5049dd296.png)

The result of dream :
The page never finishes loading and the images do not appear.
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/25438086/172014441-4ba68eea-caa6-40aa-9de1-e41f771bb985.png">

My main code : 
![image](https://user-images.githubusercontent.com/25438086/172014182-cfadadd0-f6ca-45e9-bf3a-9ea11d664934.png)

Logs :
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/25438086/172014863-16b084f0-a4f5-4b40-83e4-a88a1d9df576.png">

**Comment by dangdennis** [comment]
@aantron I'll take a look this week. Assign to me

**Comment by aantron** [comment]
> @aantron I'll take a look this week. Assign to me please

Thank you!

**Comment by dangdennis** [comment]
```
let () =
  Dream.run
  @@ Dream.logger
  @@ Dream.router [
    Dream.get "/" (Dream.from_filesystem "." "/static/index.html");
    Dream.get "/static/**" (Dream.static "./static")
  ]
```

Using the `f-static` example, I created a `static` directory with assets. My `/static/index.html` loads the image fine.

```
29.04.23 23:55:28.500       dream.log  INFO REQ 3 GET / ::1:51619 Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/112.0
29.04.23 23:55:28.500       dream.log  INFO REQ 3 200 in 542 μs
29.04.23 23:55:28.547       dream.log  INFO REQ 4 GET /static/test.jpg ::1:51619 Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Fire0
29.04.23 23:55:28.547       dream.log  INFO REQ 4 200 in 374 μs
```

The example you're using @OscarLahaie is the `w-one-binary` example though. 

Possible issues
1. your html page is referencing the images incorrectly
2. [crunch](https://github.com/mirage/ocaml-crunch) is failing to load properly. 

I'll check out the w-one-binary example and see if it works.

**Comment by dangdennis** [comment]
`w-one-binary` works fine too. I built the binary. Copied the binary out to some other area. Ran it, and it served my image. 

Can't reproduce.

**Comment by OscarLahaie** [comment]
Thank you for taking a look. I don't remember my exact mistake but it seems I was wrong. So far I have used the following system without crunch
![image](https://user-images.githubusercontent.com/25438086/235375794-502e535d-d65c-49ca-a66a-860c1039e5dd.png)

Thank you again

**Comment by aantron** [comment]
Thanks @OscarLahaie and @dangdennis!
