### ISSUE TITLE
Where is the hello.exe file?

### ISSUE THREAD

**Issue by FrankFang** [aantron/dream#23]

**Comment by aantron** [comment]
@FrankFang I'm not sure exactly what the context for your question is, however I will guess that you ran

```
dune exec --root . ./hello.exe
```

after following the rest of the [Getting started](https://github.com/aantron/dream#getting-started) instructions. In that case, `hello.exe` should have been built by Dune in `_build/default/hello.exe` (and Dune should already have run it).

**Comment by FrankFang** [comment]
Sorry I am a newbie to OCaml and ReasonML.
When I follow the instructions of [README](https://github.com/aantron/dream#getting-started), I have no idea when and how `hello.exe` was generated. And I did see `hello.exe` in the [example](https://github.com/aantron/dream/tree/master/example/1-hello)

**Comment by aantron** [comment]
No worries. Have you found it now?

**Comment by zeknas** [comment]
@FrankFang in the build command, "hello.exe" is a parameter indicating the wanted target. This exe file does not exist in the folder.

**Comment by aantron** [comment]
@FrankFang, I've switched the project to recommend building the examples with esy, and added info about where the binaries get built. So thanks for asking this question!

1. The text of example [**`1-hello`**](https://github.com/aantron/dream/tree/master/example/1-hello#files) now recommends these commands to build it:

    ```
    $ npm install esy && npx esy
    $ npx esy start
    ```

    There is no longer a potentially confusing reference to `hello.exe`. As @zeknas said, `hello.exe` is the name of a desired output file, not a file that is present in the example at the start.

    After running the commands, the example hints that the generated `hello.exe` can be copied out of esy's build sandbox like this:

    ```
    $ npx esy cp '#{self.target_dir}/default/hello.exe' .
    ```

2. There is now a [quick start script](https://github.com/aantron/dream#quick-start), which automatically downloads and builds one of the examples and has instructions for what to do next. They include:

    ```
    The built server binary can be copied out with:

      cd ./2-middleware
      npx esy cp '#{self.target_dir}/default/middleware.exe' .
    ```

**Comment by FrankFang** [comment]
Thanks!
