### ISSUE TITLE
Upgrade OCaml version in examples or just relax the constraint

### ISSUE THREAD

**Issue by aantron** [aantron/dream#256]
There is no reason, at this point, to be on 4.12.x. Dream is installable on 5.0.0.

This issue is about going through all the example `esy.json` files, changing the compiler version constraint, and trying one example (for instance, the quick start script) to make sure a newer compiler gets installed. The first `esy.json` is [here](https://github.com/aantron/dream/blob/fcc618d2006ceb06e8640e96fa9ac71ee71a6d3a/example/1-hello/esy.json).

**Comment by unoexperto** [comment]
Sorry, it's my first hour with Ocaml but what should I do to use Ocaml 5.0 with esy? I get following error now

```
No package matching:

  ocaml@>=5.0.0 <5.1.0
```
