### ISSUE TITLE
How to remove a single field from a session?

### ISSUE THREAD

**Issue by rawleyfowler** [aantron/dream#284]
Given a session with a field `foo` how can I remove just the `foo` field without invalidating the whole session?

**Comment by aantron** [comment]
Thanks! The [above commit](https://github.com/aantron/dream/commit/7a2c5a03ffb60e1fef7ea1f66ad304d518577ec4) adds [`Dream.drop_session_field`](https://aantron.github.io/dream/#val-drop_session_field), which should do what you are requesting. It was indeed missing.

**Comment by rawleyfowler** [comment]
@aantron Thanks a lot!
