### ISSUE TITLE
error when running tests: SSL 2.0 was deprecated in 2011 by RFC 6176.

### ISSUE THREAD

**Issue by mattmarcello** [aantron/dream#286]
After cloning the repo recursively to pull in submodules and running `make deps`, followed by `make test`, I see an error generated by the vendered library `gluten`.

```
File "src/vendor/gluten/lwt-unix/ssl_io.real.ml", line 95, characters 38-48:
Error (alert deprecated): SSLv23
SSL 2.0 was deprecated in 2011 by RFC 6176.
File "src/vendor/gluten/lwt-unix/ssl_io.real.ml", line 96, characters 37-47:
Error (alert deprecated): SSLv23
SSL 2.0 was deprecated in 2011 by RFC 6176.
File "src/vendor/gluten/lwt-unix/ssl_io.real.ml", line 109, characters 38-48:
Error (alert deprecated): SSLv23
SSL 2.0 was deprecated in 2011 by RFC 6176.
File "src/vendor/gluten/lwt-unix/ssl_io.real.ml", line 110, characters 37-47:
Error (alert deprecated): SSLv23
SSL 2.0 was deprecated in 2011 by RFC 6176.
make: *** [test] Error 1
```

Anyone have thoughts here?

**Comment by aantron** [comment]
Thanks for the report! These variands were deprecated by ocaml-ssl in ocaml-ssl 0.6.0. Gluten, which is vendored by Dream, was adapted to these deprecations in https://github.com/anmonteiro/gluten/pull/58. I've advanced the Gluten commit that Dream uses to include https://github.com/anmonteiro/gluten/pull/58 in 8140a600e4f9401e28f77fee3e4328abdc8246ef. I tested this locally -- please let me know if it still doesn't work for you after updating Dream to the latest `master`, including the submodules (you can also try a fresh recursive checkout).

**Comment by mattmarcello** [comment]
works!  thx.
