### ISSUE TITLE
Missing livereload in alpha 5

### ISSUE THREAD

**Issue by Naora** [aantron/dream#295]
Hi. 
I'm pretty new in the Ocaml world. So please bear with me if I missed something.
It seems that the last alpha5 package is missing the live reload feature.

I looked into the released commit and it should be available.
https://github.com/aantron/dream/commit/7b46896bf9f9ac7851234d4f3b7e82f8195da671

However, when i downloaded the released package it is missing :
![image](https://github.com/aantron/dream/assets/2221163/b9c1608d-a21f-4dec-8ec2-702cbdb542a2)

I'm not sure where the issue is. Maybe there is some caching in the CI ?

I hope this helps.

Have a nice day.

**Comment by aantron** [comment]
Hi! Live reload is in Dream `master` only for now. Unfortunately, the docs are misleading in this regard, as they were regenerated from `master` at some point :(

**Comment by Naora** [comment]
Ok then I close this. Thanks for your work. Cya
