### ISSUE TITLE
Upper bounds are needed on Caqti_lwt

### ISSUE THREAD

**Issue by dysinger** [aantron/dream#301]
2.0.0 removes some libraries that Dream depends on

**Comment by paurkedal** [comment]
I'm hoping for an upgrade instead (#302).

If you are referring to the `Pool` and `connect*` functions, those were moved into a sub-library `caqti-lwt.unix` to make space for shared code when introducing caqti-mirage.

**Comment by aantron** [comment]
Addressed by #302. Thank you!
