### ISSUE TITLE
[Documentation] tutorial on how to deploy a dream web server on a hosted service

### ISSUE THREAD

**Issue by aryx** [aantron/dream#32]
Do you have any tips on how to deploy a dream web server for real, on the web, easily?
Do you personally use AWS? google cloud? Or something like Linode? How do you scale it?

**Comment by aantron** [comment]
No tips at the moment. I added a TODO item for working out AWS deployment after the forum discussion. However, I also took a minor break, so I haven't gotten around to it yet. I plan to add it before release, and will definitely ping this issue, a well.

I don't have direct experience with scaling beyond a couple Digital Ocean machines. Whenever I worked on a large enough project, we had an ops team doing that.

The project that motivated Dream hasn't reached that scale yet, not even close :) However, outside that project, I intend to run at least some synthetic tests on a fake large Dream deployment.

**Comment by aantron** [comment]
@aryx I've added several [deployment examples](https://github.com/aantron/dream/tree/master/example#deploying):

- [Heroku](https://github.com/aantron/dream/tree/master/example/z-heroku#files) ([live](https://dream-example.herokuapp.com/)), with a [CI script](https://github.com/aantron/dream/blob/master/.github/workflows/heroku.yml) for deploying from GitHub Actions. Heroku has built-in [scaling support](https://devcenter.heroku.com/articles/scaling), at the price of putting constraints on your app's environment.
- [Digital Ocean with Docker](https://github.com/aantron/dream/tree/master/example/z-docker#files).
- [Digital Ocean, as a systemd daemon](https://github.com/aantron/dream/tree/master/example/z-systemd#files).

In addition, the new [playground](http://dream.as) is itself deployed to Digital Ocean as a [systemd daemon](https://github.com/aantron/dream/blob/master/example/z-playground/server/playground.service), and can serve as a small but real example.

I will probably add an AWS example later on in development, as Dream becomes more mature. Heroku and Digital Ocean should be sufficient for medium-traffic applications, but AWS (or Azure, Google Cloud) will be necessary for huge deployments.

**Comment by aryx** [comment]
Fantastic!

**Comment by aryx** [comment]
thx a lot!

**Comment by aryx** [comment]
Note that I get a 404 on the link https://github.com/aantron/dream/blob/heroku-ci/.github/workflows/heroku.yml mentioned in the 
https://github.com/aantron/dream/tree/master/example/z-heroku#files

**Comment by aantron** [comment]
Thanks, fixed it!
