### ISSUE TITLE
Add dream to Nixpkgs for use with flakes

### ISSUE THREAD

**Issue by Ajlow2000** [aantron/dream#322]
I am just diving into ocaml and setting up my [project flake](https://nixos.wiki/wiki/Flakes) but ran into a wall when dream wasn't in the [nixpkgs repo](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=ocamlPackages.dream).  

Many other ocaml libraries are supported ([example](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=ocamlPackages)) and I would like to add dream to the list. 

Worth noting, I have been using nixos/flakes for about a year now but haven't had cause to get involved with contributing to the project before.  I would love to tackle this project, but would also appreciate guidance along the way.  [Here is the guide for adding a package from the nixpkgs repo itself.](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md).

I opened this issue to give the dream team (lol) a chance to comment on this or make me aware of any ongoing project that is  similar.  I believe the actual work for this will get done on the nixpkgs repo.

**Comment by kentookura** [comment]
Have you tried [opam-nix](https://github.com/tweag/opam-nix/tree/main)? You can use every package in [opam-repository](https://github.com/ocaml/opam-repository) without it being part of nixpkgs. If you want, I can provide you with an example flake.

**Comment by Ajlow2000** [comment]
Oh interesting. This seems far more ergonomic.  If you have anflaoe you could link I suppose I'd appreciate it. But there seems to be pretty good documentation already. I'll have to play with it after work

**Comment by lokasku** [comment]
I managed to install the Dream package with Nix using the overlay from [`nix-ocaml`](https://github.com/nix-ocaml). You could use [what has already been done there](https://github.com/nix-ocaml/nix-overlays/tree/master/ocaml/dream). Personally, using their overlay, I got it to work with this flake :
```nix
{
  inputs.nixpkgs.url = "github:nixOS/nixpkgs";

  inputs.ocaml-overlay.url = "github:nix-ocaml/nix-overlays";
  inputs.ocaml-overlay.inputs.nixpkgs.follows = "nixpkgs";


  outputs = { self, nixpkgs, ocaml-overlay }:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs {
        inherit system;
        overlays = [
          ocaml-overlay.overlays.default
        ];
      };
    in
    {
      devShell.${system} = pkgs.mkShell {
        buildInputs = with pkgs; [
          opam
          ocaml
          dune_3
          ocamlPackages.findlib
        ] ++ [ ocamlPackages.dream ];
      };
    };
}
```

**Comment by Ajlow2000** [comment]
Yes, after playing with this a bit I think I find this solution preferable as well. Closing this issue. Thanks everyone!
