### ISSUE TITLE
HTML Attributes that have a `:` in the middle of the name truncate everything before the `:`

### ISSUE THREAD

**Issue by briangwaltney** [aantron/dream#324]
```ocaml
Dream.html {|<div my:attr="test"></div>|}
```
The above code will produce:

```html
<div attr="test"></div>
```
as output.

This prevents many features in common libraries like Alpinejs that utilize attributes with this style.

**Comment by briangwaltney** [comment]
This is an issue with `Dream_livereload` not with Dream. Sorry...

**Comment by aantron** [comment]
Reopening, as `Dream_livereload` was merged into Dream (in somewhat modified form).

**Comment by maxRN** [comment]
Was able to reproduce. Most likely the same bug as in https://github.com/aantron/lambdasoup/issues/12

**Comment by aantron** [comment]
@maxRN thank you! If you are interested, could you check what these selectors should parse as according to the [spec](https://www.w3.org/TR/selectors/)?

**Comment by aantron** [comment]
Disregard my message, which I deleted. Had a fog brain moment.

**Comment by aantron** [comment]
@maxRN would you be able to try your repro again with your PR https://github.com/aantron/lambdasoup/pull/61 (thank you!)? A pin `opam pin lambdasoup --dev-repo` should be sufficient IIRC, as the PR is now merged.

**Comment by aantron** [comment]
Many thanks!

**Comment by aantron** [comment]
@maxRN for the repro and fix, @briangwaltney for the report and patience!
