### ISSUE TITLE
Dream with Async

### ISSUE THREAD

**Issue by imeckler** [aantron/dream#329]
First off thank you for writing this, it's a lovely library. I was just wondering how involved it might be to refactor Dream to have both an Lwt and Async implementation? I see there is a WIP Eio branch so perhaps that would be sufficient for my purposes.

**Comment by aantron** [comment]
Thank you! Dream will probably switch to Eio and fully direct-style code, exclusive of Lwt and Async, so I think I'd prefer to close this as not planned for now. We might reconsider this in the future, depending on how Eio adoption goes.
