### ISSUE TITLE
Get an SSL (or Lwt_unix?) error on concurrent connection

### ISSUE THREAD

**Issue by Nymphium** [aantron/dream#33]
I get an SSL error under the below settings:
- running [6-echo](https://github.com/aantron/dream/tree/master/example/6-echo) server with `~https:true`
- run [`ab`](https://httpd.apache.org/docs/2.4/programs/ab.html) command with 2 or more concurrency level

  ```
  $ ab -n 2 -c 2 -f TLS1.3 -T 'application/text' -p <(echo hi) https://localhost:8080/echo
  ```

error log:
```
15.04.21 00:55:12.132       dream.log  INFO REQ 1109 POST /echo 127.0.0.1:35012 ApacheBench/2.3
15.04.21 00:55:12.132       dream.log  INFO REQ 1109 200 in 40 μs
15.04.21 00:55:12.137       dream.log  INFO REQ 1110 POST /echo 127.0.0.1:35014 ApacheBench/2.3
15.04.21 00:55:12.137       dream.log  INFO REQ 1110 200 in 41 μs
15.04.21 00:55:12.138      dream.http ERROR HTTP (127.0.0.1:35016): SSL read() error: error:00000000:lib(0):func(0):reason(0)
15.04.21 00:55:12.138      dream.http ERROR Raised by primitive operation at Lwt_unix.shutdown in file "src/unix/lwt_unix.cppo.ml", line 1677, characters 2-38
15.04.21 00:55:12.138      dream.http ERROR Called from Lwt.Miscellaneous.wrap2 in file "src/core/lwt.ml", line 3087, characters 15-24
```

**Comment by aantron** [comment]
Thanks for the report, I was able to reproduce it, and I'm looking into it. Intially, I can say that this looks like a low-level/upstream error.

**Comment by aantron** [comment]
The error appears to occur *after* the last request for me. Can you confirm? For example, if I do

```
$ ab -n 100 -c 2 -f TLS1.3 -T 'application/text' -p <(echo hi) https://localhost:8080/echo
```

the error is triggered *after* request 100 has been finished, presumably when the TLS session (or one of them) is closed.

**Comment by aantron** [comment]
However, this doesn't explain the client port number, which appears to be fresh. Is it possible that this is a bug in `ab`?

**Comment by Nymphium** [comment]
I think this might be a bug in `ab`, too. Sorry ;)

I confirm no error with below script:
```bash
function post() {
  for ((i=0;i<100;i++)) {
    curl -s -k --http2 -XPOST https://127.0.0.1:8080/echo -d 'hello' &
  }
}
```

**Comment by aantron** [comment]
> I confirm no error with below script:

Thanks!

As for the issue, I did not know about `ab` before, so it's useful :) Apart from the spurious error, it's a nice tool, and I will use it.
