### ISSUE TITLE
Update and fix CI/CD pipeline

### ISSUE THREAD

**Issue by maxRN** [aantron/dream#338]
The pipeline doesn't run and is using outdated actions (`avms/setup-ocaml@v2` was superseded by the official `ocaml/setup-ocaml` action).

We can copy some of the setup from how dune does it: https://github.com/ocaml/dune/blob/main/.github/workflows/workflow.yml

I'm currently working on a possible implementation here: https://github.com/aantron/dream/pull/337

**Comment by aantron** [comment]
Thanks! I've got a parallel PR in #335 doing some of the same things, though my plan was to work on it slowly. You're welcome to pull in commits from it and I'll merge the whole thing together with due credit. In particular, I have the build working on recent versions, see the two commits there (https://github.com/aantron/dream/pull/335/commits/8d0bd88cc375dc5df6c7bc216aae04ba93e4f4eb, https://github.com/aantron/dream/pull/335/commits/c9db203d901e07efc5d592207674659e30024b8b).

```
CI: test only on OCaml 4.13 and higher

Dream no longer installs on lower OCaml versions, because mirage-crypto
requires OCaml 4.13. See

  https://github.com/mirage/mirage-crypto/pull/233

The reason for mirage-crypto requiring 4.13 seems to be minor
convenience, and isn't justified in my opinion. However, Dream itself
will likely require OCaml 5 in the medium term due to upgrading to
multicore and effects, so it seems unnecessary to make an effort to
restore 4.08 support at this point.
```

```
Exclude dream-mirage.opam from main CI

dream-mirage has additional dependencies that may be slower to update,
or otherwise cause package conflicts. It's only needed for the mirage
test, not for the main test suite of Dream.
```
