### ISSUE TITLE
w-watch build instructions fail

### ISSUE THREAD

**Issue by LAC-Tech** [aantron/dream#350]
```
[lewis@lightgrey w-watch]$ ls
dune  dune-project  hello.ml  README.md  w-watch.opam
[lewis@lightgrey w-watch]$ opam install --deps-only --yes .
[WARNING] Failed checks on w-watch package definition from source at
          file:///home/lewis/code/dream/example/w-watch:
    error 23: Missing field 'maintainer'
  warning 25: Missing field 'authors'
  warning 35: Missing field 'homepage'
  warning 36: Missing field 'bug-reports'
    error 57: Synopsis and description must not be both empty
[lewis@lightgrey w-watch]$ opam --version
2.1.6
[lewis@lightgrey w-watch]$ ocaml --version
The OCaml toplevel, version 5.2.0
```

**Comment by aantron** [comment]
I also get this output

```
[WARNING] Failed checks on w-watch package definition from source at
          file:///home/lewis/code/dream/example/w-watch:
    error 23: Missing field 'maintainer'
  warning 25: Missing field 'authors'
  warning 35: Missing field 'homepage'
  warning 36: Missing field 'bug-reports'
    error 57: Synopsis and description must not be both empty
```

but it's not actually an error, and I can continue with the instructions. Are you unable to continue?

I do get the extra output

```
Nothing to do.
# Run eval (opam env) to update the current shell environment
```

The only environment variable I am spotting that might affect this in my understanding is `OPAMSTRICT`, but it doesn't seem to convert this `[WARNING]` into an `[ERROR]`, and I get another error with it instead:

```
[ERROR] undefined filter variable in dependencies of ambient-context.0.1.0:
        with-dev-setup
```

Is there anything different about your environment variables or setup otherwise?

**Comment by LAC-Tech** [comment]
Just re-confirmed - get absolutely no prompt after "error 57".

"OPAMSTRICT" does not appear to be set. Here's a list of all my Ocaml related envars, happy to check any specific ones.

CAML_LD_LIBRARY_PATH=/home/lewis/.opam/5.2.0/lib/stublibs:/home/lewis/.opam/5.2.0/lib/ocaml/stublibs:/home/lewis/.opam/5.2.0/lib/ocaml
OCAML_TOPLEVEL_PATH=/home/lewis/.opam/5.2.0/lib/toplevel
OPAM_SWITCH_PREFIX=/home/lewis/.opam/5.2.0

It looks like I am able to continue, but my immediate impression (and I imagine a lot of other peoples impression) is seeing a handful of errors and assuming a bug.

**Comment by aantron** [comment]
Yes, I think it's worth adding enough to the opam files to suppress these outputs. Will fix that soon. Thank you!
