### ISSUE TITLE
Dream.run "starter" behavior: don't wait for ENTER, get rid of grace delay

### ISSUE THREAD

**Issue by aantron** [aantron/dream#46]
It's probably enough to just ask people to press Ctrl+C to exit (it already works). As for the 1-second grace delay, it's probably unnecessary for starter code &mdash; but needed in robust Web apps, later in development. However, a robust Web app is already probably at least a medium-sized project that can afford to, and needs to, implement its own exit logic. That means the default grace delay is likely redundant in all cases.

cc @Lupus

**Comment by yawaramin** [comment]
Just a note that `~stop_on_input` is still mentioned in `dream.mli`, that should probably also be removed.

**Comment by aantron** [comment]
Thank you! Removed in d0887715121217070d6a62f8ade1dd3d24cf8e96.
