### ISSUE TITLE
JSON example build issues

### ISSUE THREAD

**Issue by abedra** [aantron/dream#54]
There appears to be a gluten dependency in the `e-json` example project that's not easily resolved. Trying to build results in the following:

```sh
npx esy            
info esy 0.6.10 (using dream.opam) found project at ~/src/opensource/dream/
File "src/vendor/dune", line 39, characters 11-26:
39 |   (modules gluten_lwt_unix tls_io ssl_io)))
                ^^^^^^^^^^^^^^^
Error: Module Gluten_lwt_unix doesn't exist.
error: command failed: 'dune' 'build' '-p' 'dream' '-j' '4' (exited with 1)
esy-build-package: exiting with errors above...
error: build failed with exit code: 1
  
esy: exiting due to errors above
```
I naturally tried to install the module but it has a conflict:

```sh
opam install gluten-lwt-unix
The following actions will be performed:
  ⊘ remove  dream           1.0.0~alpha1 [conflicts with gluten]
  ∗ install gluten          0.2.1        [required by gluten-lwt-unix]
  ∗ install gluten-lwt      0.2.1        [required by gluten-lwt-unix]
  ∗ install gluten-lwt-unix 0.2.1
===== ∗ 3   ⊘ 1 =====
Do you want to continue? [Y/n] 
```

Is there a good way to work through this?

**Comment by aantron** [comment]
@abedra This looks strange, like a failed recursive checkout by esy, or some sort of race condition. I tried just now, and wasn't able to reproduce it. Specifically, I took the quick start script:

```
curl -fsSL https://raw.githubusercontent.com/aantron/dream/master/example/quickstart.sh > quickstart.sh
```

opened it up and replaced `2-middleware` by `e-json`:

```diff
-EXAMPLE=2-middleware
+EXAMPLE=e-json
```

and ran it:

```
bash quickstart.sh
```

it built everything and works as expected for me.

The version of Dream that esy grabbed was:

```
$ npx esy ls-builds
├── @opam/dream@github:aantron/dream:dream.opam#9a11c79fb147df84517442a299822f2218be5ff5 [built]
```

what do you have in your build?

> I naturally tried to install the module but it has a conflict:

The published one in opam is different (for now) from the vendored one in Dream. Dream wouldn't pick up the published one anyway (in favor of the vendored one). Also, it wouldn't (or shouldn't!) pick up stuff from `opam` while building with `esy`.

**Comment by aantron** [comment]
> ```shell
> info esy 0.6.10 (using dream.opam) found project at ~/src/opensource/dream/
> ```

Looking more closely at this line, it appears you are in the root directory of a Dream clone. Try going to `example/e-json` and running the build commands from there. Most likely (could be wrong), you cloned Dream, but not recursively (`--recursive`), so now you can't build the base project directly (until you do a recursive clone or pull in the vendored submodules, see [CONTRIBUTING.md](https://github.com/aantron/dream/blob/master/docs/CONTRIBUTING.md)). However, that doesn't matter for building the examples from esy, from their respective `example/*` directories.

**Comment by aantron** [comment]
To clarify that further, if you build from `example/e-json`, esy will do its own internal recursive clone of Dream, will all the right flags for getting all the vendored code.

**Comment by aantron** [comment]
The commit linked above updates all the examples to show a `cd` command, to be explicit about the directory the build commands should be run from. For example, see [**`e-json`**](https://github.com/aantron/dream/tree/master/example/e-json#readme) now.

**Comment by abedra** [comment]
Thanks for the advice here. While I was in the `e-json` directory, I hadn't pulled the submodules. Once I did things cleared up. Does this mean I will need to have projects refer to a cloned dream repository to make sure I pick up the vendored code if I want to make something json based?

**Comment by aantron** [comment]
> Does this mean I will need to have projects refer to a cloned dream repository to make sure I pick up the vendored code if I want to make something json based?

No, examples, and especially your own projects, build without having to maintain a clone. esy pulls git submodules automatically.

**Comment by abedra** [comment]
Thank you!
