### ISSUE TITLE
Support 100 Continue responses that don't end the current request

### ISSUE THREAD

**Issue by aantron** [aantron/dream#61]
When the server gets [`Expect: 100-continue`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/100) from the client, it should be able to send a 100 Continue response and go on processing the request, eventually sending the "real" response.

AFAIK, supporting this will require patching http/af. The Dream API will look something like

```ocaml
Dream.send_response : request -> response -> unit promise
```

...where `response` will then be ``Dream.response ~status:`Continue ""`` or `Dream.response ~code:100 ""`.

cc @anuragsoni

**Comment by aantron** [comment]
@anuragsoni how "important" is this, in your experience? Is it only curl (and similar) that sends `Expect: 100-continue` in practice (in contrast to browsers)?

**Comment by anuragsoni** [comment]
> @aantron  how "important" is this, in your experience? Is it only curl (and similar) that sends `Expect: 100-continue` in practice (in contrast to browsers)?

I'd guess this isn't too important. I don't think browsers make use of this. In theory any http spec compliant client can attempt to use this, but i'll admit i've only seen this in curl.

**Comment by aantron** [comment]
Thanks. I *would* still like to support it, but I was wondering how urgent it is and how much we should pester upstreams :P

**Comment by aantron** [comment]
I'm going to close this for now, but if anyone runs into needing this, please ping the issue.

**Comment by cemerick** [comment]
Just here to leave a breadcrumb to https://github.com/c-cube/ezcurl/issues/12; it ended up being important in that context because libcurl will wait for a full second before sending the request body, _if it doesn't know its size_. There is a client-side workaround, but if one weren't in control of the client, lack of support here for `100 Continue` would be unfortunate.
