### ISSUE TITLE
install breaks

### ISSUE THREAD

**Issue by iljavs** [aantron/dream#63]
I tried to follow the quick start install instructions. didn't work :(: 
ilja@meatdripper:~/dream/example/2-middleware$ npm install esy && npx esy

> esy@0.6.10 postinstall /home/ilja/dream/example/2-middleware/node_modules/esy
> node -e "process.env['OCAML_VERSION'] = process.platform == 'linux' ? '4.10.1002-musl.static.flambda': '4.10.0'; process.env['OCAML_PKG_NAME'] = 'ocaml'; require('./postinstall.js')"

importing: esy-2c95689b
Done!
npm WARN saveError ENOENT: no such file or directory, open '/home/ilja/dream/example/2-middleware/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/ilja/dream/example/2-middleware/package.json'
npm WARN 2-middleware No description
npm WARN 2-middleware No repository field.
npm WARN 2-middleware No README data
npm WARN 2-middleware No license field.

+ esy@0.6.10
added 1 package and audited 1 package in 4.082s
found 0 vulnerabilities

info esy 0.6.10 (using esy.json)
info checking https://github.com/ocaml/opam-repository for updates...
info checking https://github.com/esy-ocaml/esy-opam-override for updates...
info resolving esy packages: done
info solving esy constraints: done
info resolving npm packages: done
info fetching: done
.... installing @opam/bigarray-overlap@opam:0.2.0@d8a38f4aesy: internal error, uncaught exception:
     Unix.Unix_error(Unix.EACCES, "rename", "/home/ilja/.esy/source/s/yarn_pkg_config__9829fc81")
     Raised at file "src/core/lwt.ml", line 2999, characters 20-29
     Called from file "src/unix/lwt_main.ml", line 26, characters 8-18
     Called from file "esy-lib/Cli.re", line 264, characters 9-28
     Called from file "cmdliner_term.ml", line 25, characters 19-24
     Called from file "cmdliner.ml", line 25, characters 27-34
     Called from file "cmdliner.ml", line 116, characters 32-39
.... installing @opam/cstruct@opam:6.0.0@c77fb059ilja@meatdripper:~/dream/example/2-middleware$

**Comment by aantron** [comment]
Heya, this looks like a likely upstream error in esy. See https://github.com/esy/esy/issues/1097. The only thing that worries me is that in your case, the error occurred in `~/.esy`, whereas I've only seen it on Windows and in `./_esy` so far. Trying again often works. I'm guessing that since you issued the commands manually, however, trying again didn't work in your case.

cc @ManasJayanth

What happens if you delete `~/.esy`, re-clone the Dream repo, and try again? Also, what system are you on?

**Comment by ManasJayanth** [comment]
Thanks for the report. Is there a way to reproduce this? Unfortunately, I can't reproduce this locally.

**Comment by aantron** [comment]
@ManasJayanth The next time I get it, I'll try to reproduce it with a dev version of esy. When I get it, I can usually reproduce it over a stretch of time, so hopefully we can finally at least diagnose this. However, I don't know how long it will be until it occurs.

**Comment by aantron** [comment]
I'm going to close this as likely fixed by https://github.com/esy/esy/pull/1386.
