### ISSUE TITLE
(newb) `npx esy` fails but separate dune instructions work [waiting on #63]

### ISSUE THREAD

**Issue by yatesco** [aantron/dream#69]
(I'm not being self-deprecating, I really am a newbie at OCaml, `dune` and `esy`, so it is almost certainly something I'm doing!)

Hi - I'm on macOS and trying out https://github.com/aantron/dream/tree/master/example/w-fullstack-jsoo. Following the `esy` route produces:
```
➜  w-fullstack-jsoo git:(master) ✗ npx esy
info esy 0.6.10 (using esy.json)
cp: static/client.js: Operation not permitted
error: command failed: 'cp' '_build/default/client/client.bc.js' 'static/client.js' (exited with 1)
esy-build-package: exiting with errors above...
error: build failed with exit code: 1
 
esy: exiting due to errors above
```

However, if I do the listed `dune` steps then after following the `dune`/`opam` prompted instructions to install missing bits then it all works. If I run `npx esy` again I get the above error.

I also got a similar experience with the other full stack tutorials.

I haven't the first clue as to _what_ is causing the problem so I thought I would start here :-).

**Comment by aantron** [comment]
Thanks. It's probably an error in how I've set up the esy build, namely esy builds inside a sandbox directory that it creates, and I haven't accounted for that. I'll look through the examples' esy setups shortly, and fix these errors.

**Comment by aantron** [comment]
Just want to ping this to say I am working on it. I reproduced #63 while doing so, which temporarily prevents me from working on this issue, but is a good thing because we need to fix #63. However, I had to slow down and didn't have time to investigate the broken install, but should do so shortly.

**Comment by aantron** [comment]
I wasn't able to reproduce this on my machine (WSL Ubuntu 20.04). I'll try to see if someone on Mac is able to observe it.

**Comment by aantron** [comment]
Tried with both esy `master` (esy/esy@ca4e8efaeebf251c90b5a302a4d2006de078522c) and 0.6.10 from npm.

**Comment by ulrikstrid** [comment]
@yatesco you can set this: `"buildsInSource": "unsafe",` to fix the issue

**Comment by ulrikstrid** [comment]
Another thing to not, `"unsafe"` sounds... unsafe. But it just means that esy won't sandbox your project directory so you're allowed to write into it during builds.

**Comment by yatesco** [comment]
yep, confirmed that `"buildsInSource": "unsafe"` works.

(As an aside, it was set to `_build` not `build` before.

**Comment by aantron** [comment]
Thanks @yatesco for the report and patience, and @ulrikstrid for confirmation and the fix!



> (As an aside, it was set to `_build` not `build` before.)

Oops! I did mean `_build` in my comment, my mistake.
