### ISSUE TITLE
form target attribute

### ISSUE THREAD

**Issue by zoggy** [aantron/dream#73]
Hi, 

it would be great if ``form_tag`` could accept an optional argument ``target`` to be able to specify for example "_blank" so that the browser will submit the form in another tag/window.

**Comment by aantron** [comment]
Thanks! The linked commit adds `?target`.

**Comment by aantron** [comment]
Note that in the upcoming release, `form_tag` has been superseded by [`csrf_tag`](https://aantron.github.io/dream/#val-csrf_tag), which generates only the `<input>` tag, so you can write the `<form>` tag directly. See #201.
