### ISSUE TITLE
Add node_modules to dune's ignored directories in all examples

### ISSUE THREAD

**Issue by aantron** [aantron/dream#85]
To speed up Dune builds when also using npm, so Dune doesn't scan `node_modules` needlessly, since `node_modules` can be quite large.

This is especially important when doing live reloading.

cc @thangngoc89 

The full-stack examples already have this. It just needs to be done in all the examples, since eventual npm usage is likely in all cases.

https://github.com/aantron/dream/blob/500f4d0d37e5b0dcc4d4283ef5a36f2226c6caea/example/w-fullstack-rescript/dune#L1

**Comment by tcoopman** [comment]
Be careful with this in the melange examples. Melange adds a `data_only_dirs` stanza and dune doesn't want you to define more than 1 (https://github.com/melange-re/melange/issues/204)

**Comment by aantron** [comment]
Right, thanks @tcoopman. Was also pointed out by @anmonteiro on Discord. The current Melange example doesn't have that stanza at all, and additionally we'll need to add text to the example pointing this out, so that if a person starts from another example, they have a reasonable chance of finding out that they should delete it.
