### ISSUE TITLE
Trouble building a dream project with dune

### ISSUE THREAD

**Issue by roehst** [aantron/dream#9]
Hi, I saw Dune on Lobste.rs and the design looks real good!

I tried to run in my machine with no success.

My project consists of:
- dune
```
(executable
   (name main)
   (libraries dream))

```
- dune-project
```
(lang dune 2.0)
```
- main.ml
```
let () =
  Dream.run (fun _ ->
    Dream.respond "Good morning, world!")
```

When I do `dune build`, I get this error:

```
Entering directory '/Users/rodrigo/dream'
File "dream/src/vendor/h2/lib/settings.ml", line 284, characters 7-28:
284 |        Angstrom.parse_string
             ^^^^^^^^^^^^^^^^^^^^^
Error: This function has type 'a Angstrom.t -> string -> ('a, string) result
       It is applied to too many arguments; maybe you forgot a `;'.
```

my opam is 2.0.8, ocaml is 4.10.2, running on windows

also, `opam install dream` does not work for me:

```
opam install dream
[ERROR] No package named dream found.
```

Can anyone help me? Thanks in advance.

**Comment by aantron** [comment]
Hi! This is probably an issue with some incompatible versions of dependencies.

I assume you cloned Dream. Go to the clone's root, and run

`opam install --deps-only .`

That should install a consistent set of deps.



> also, `opam install dream` does not work for me:

Yes, Dream is unreleased :) I only made the repo public, but haven't announced or published the actual package yet :) As you can see in the README,

> *TODO opam release, esy instructions, quick-start script.*

I should probably clarify this message slightly, and add more accurate instructions for people that want to try it this early!

**Comment by aantron** [comment]
Added this to the [README](https://github.com/aantron/dream#getting-started):

> Dream is not yet announced or released! Before release, Dream will get a quick-start script, and some other help for getting started quickly. However, if you want to try Dream now, you can do:
>
> ```
> git clone https://github.com/aantron/dream.git --recursive
> cd dream
> opam install .
> ```
>
> After that, go to one of the examples, such as [**`1-hello`**](https://github.com/aantron/dream/tree/master/example/1-hello#files), and try building it:
>
> ```
> cd example/1-hello
> dune exec --root . ./hello.exe
> ```
>
> You should be able to copy the example out to a completely separate directory, if you didn't use a local `_opam` switch scoped to Dream's clone directory. If you did, you can pin Dream to your clone in a different opam switch with
>
> ```
> opam pin add dream /path/to/your/clone
> ```

If that doesn't fix it, could you say what you did to install Dream and/or its deps, and show the version of package `angstrom` with `opam list --installed angstrom`?

**Comment by roehst** [comment]
Hi aantron, thanks, I will try this as soon as I finish work. Really excited to test this :)

**Comment by roehst** [comment]
@aantron it worked simply by using `opam install .` in the repo folder (and i didnt clone recursively)

Will try the framework later tonight :) thanks a lot

**Comment by roehst** [comment]
Hi, it worked very well indeed! This is just what I was looking for ages. A very simple, minimal version of Sinatra or Flask.

I tested with this program:

https://gist.github.com/roehst/44b002632ae0489b3ddafcb8df56193e

**Comment by aantron** [comment]
Great :) and thanks for the gist!
