### ISSUE TITLE
Dream.flash_message should provide debug mode

### ISSUE THREAD

**Issue by thangngoc89** [aantron/dream#90]
From my experience adding flash message, it could be extremely frustrating to debug why flash messages aren't rendered at all. 

I wrote this little middleware to help with debugging but this should probably be added to `Dream.flash_message` directly 

```ocaml
type flash = (string * string) list [@@deriving show]

let debug_flash inner_handler request =
  let%lwt response = inner_handler request in
  let local = Dream.get_flash request in
  Dream.log "flash messages: %s" (show_flash local) ;
  Lwt.return response
```

**Comment by aantron** [comment]
I guess there should probably be a `dream.flash` log source. Dream also needs a neat way to set the log level per-source, and then flash messages need documentation about the existence of verbose logging on `dream.flash` at level debug. Would that do?

**Comment by aantron** [comment]
A good place for such documentation might be the not-yet-integrated [flash message example](https://github.com/aantron/dream/tree/809835dcfe655bbe2fd811acae4ddecd6f1800b4/example/b-flash-message), which also needs a README.

**Comment by aantron** [comment]
The flash message middleware should probably also warn if the whole encrypted cookie is more than 4096 bytes long.
