### ISSUE TITLE
Recommend a more Web-friendly and modern ocamlformat config, or PR to ocamlformat

### ISSUE THREAD

**Issue by aantron** [aantron/dream#94]
ocamlformat by default does things like

```ocaml
{ foo = a
; bar = b
; baz = c
}
```

which is completely unnecessary, ugly, and would be actually better in terms of being able to reorder lines without changing them at all, if it emitted a more JS-like output, but with an extra trailing delimiter (supported by OCaml):

```ocaml
{
  foo = a;
  bar = b;
  baz = c;
}
```

By comparison, with the default ocamlformat output, if one wanted to reorder `foo` and `bar`, the lines would have to actually be changed.

I've been using the JS-like style (without using ocamlformat) personally for >5 years and AFAIK it is strictly more diff-friendly than ocamlformat. It is also the style of odoc's output.

There are probably other flaws, but this jumps out at me the most. It just doesn't "look" "Web" :P

cc @tmattio, @tcoopman 

About the good first issue label: if this can be done with just config, figuring it out is a good first issue.

**Comment by thangngoc89** [comment]
I absolute hate this style of ocamlformat ! still fiddling with ocamlformat configurations myself but I didn't find the suitable config to tune this

**Comment by mooreryan** [comment]
This is interesting.  On `ocamlformat v0.18.0` with the default settings other than `--enable-outside-detected-project`, it will turn this messy file

```ocaml
type apple = { apple : int; 
pie : int; is : int; good : int; 

tasty : int }

let a = {
    apple = 123413241
    ; pie = 123412341;
is = 32412341234134;
    good = 324134543252;tasty = 23423423;}
```

to this `ocamlformat --enable-outside-detected-project apple.ml`:

```ocaml
type apple = { apple : int; pie : int; is : int; good : int; tasty : int }

let a =
  {
    apple = 123413241;
    pie = 123412341;
    is = 32412341234134;
    good = 324134543252;
    tasty = 23423423;
  }
```

**Comment by thangngoc89** [comment]
@mooreryan what is your global `.ocamlformat` looks like ?

**Comment by mooreryan** [comment]
That's a fair point about the short `match` and `@@` collapsing. I just wanted to point out that the formatting of records currently does look like the more JS style that aantron mentioned wanting.

**Comment by thangngoc89** [comment]
I'm poking around ocamlformat configs.

This makes seperator in the end position
```
break-separators = after
```

like this:

```
let a =
  { apple = 123413241;
    pie = 123412341;
    is = 32412341234134;
    good = 324134543252;
    tasty = 23423423
  }
```

This fixes `@@` collapsing
```
break-infix-before = fit-or-vertical
```

**Comment by thangngoc89** [comment]
This is my current ocamlformat:

```
version = 0.18.0
profile = conventional

leading-nested-match-parens = false 
align-constructors-decl = true
align-variants-decl = true
space-around-variants = false
space-around-arrays = false
break-before-in = auto
break-infix = fit-or-vertical
break-separators = after
space-around-records = true
```

Apart from not breaking the short match like above, I'm quite happy with this

**Comment by mooreryan** [comment]
I've just been using completely default as I'm not picky and just want someone else to decide the formatting :) but I think I will try yours for comparison

**Comment by aantron** [comment]
Interestingly, ocamlformat default seems not *too* bad in terms of what it does to lists. What are people using for ocamlformat settings that generates the `;` in the left column?

I tried this just now with ocamlformat 0.18.0:

`sample.ml`:

```ocaml
let list = [
  a_very_long_identifier_or_expression_one;
  a_very_long_identifier_or_expression_two;
  a_very_long_identifier_or_expression_three;
]
```

`.ocamlformat` is just an empty file. Then,

```
$ ocamlformat sample.ml
let list =
  [
    a_very_long_identifier_or_expression_one;
    a_very_long_identifier_or_expression_two;
    a_very_long_identifier_or_expression_three;
  ]
```

A bit suboptimal, but acceptable :)

**Comment by aantron** [comment]
Likewise,

```ocaml
type t = {
  a : string;
  b : string;
  c : string;
}

let t = {
  a = "a_pretty_long_string_to_force_separate_line";
  b = "a_pretty_long_string_to_force_separate_line";
  c = "a_pretty_long_string_to_force_separate_line";
}
```

became

```ocaml
type t = { a : string; b : string; c : string }

let t =
  {
    a = "a_pretty_long_string_to_force_separate_line";
    b = "a_pretty_long_string_to_force_separate_line";
    c = "a_pretty_long_string_to_force_separate_line";
  }
```

Again, not optimal, but acceptable.

**Comment by thangngoc89** [comment]
@aantron this would make to commas aligned to the left 

```
break-separators = before
```

**Comment by aantron** [comment]
Just found out that `profile = janestreet` seems pretty disastrous :P

```ocaml
let list =
  [ a_very_long_identifier_or_expression_one
  ; a_very_long_identifier_or_expression_two
  ; a_very_long_identifier_or_expression_three
  ]
;;

type t =
  { a : string
  ; b : string
  ; c : string
  }

let t =
  { a = "a_pretty_long_string_to_force_separate_line"
  ; b = "a_pretty_long_string_to_force_separate_line"
  ; c = "a_pretty_long_string_to_force_separate_line"
  }
;;
```

`;;` and `;` on the left.

**Comment by aantron** [comment]
> @aantron this would make to commas aligned to the left
> 
> ```
> break-separators = before
> ```

Ah, yes. Thank you.

**Comment by thangngoc89** [comment]
This is why prettier has minimal configurations.
refmt/gofmt doesn't have any configurations. The code looks the same everywhere

**Comment by aantron** [comment]
Agreed. For now, I'm thinking to PR your `.ocamlformat` suggestion above into this repo, and recommend people use that.

**Comment by aantron** [comment]
I committed @thangngoc89's [config](https://github.com/aantron/dream/issues/94#issuecomment-873449449) to get started. We can tweak it over time.

**Comment by thangngoc89** [comment]
@aantron I added the below configuration to my ocamlformat now to break all match cases instead of fitting them in the same line if possible

`break-cases = all` in `.ocamlformat`

**Comment by aantron** [comment]
> @aantron I added the below configuration to my ocamlformat now to break all match cases instead of fitting them in the same line if possible
> 
> `break-cases = all` in `.ocamlformat`

Nice. I've commited that.

**Comment by aantron** [comment]
I've added an ocamlformat [test](https://github.com/aantron/dream/tree/master/test/ocamlformat) for the config in this repo. The current expected output is:

https://github.com/aantron/dream/blob/a169c107b062485e4529118540e9d4cc951d8cfa/test/ocamlformat/test.expect.ml#L1-L68

If you find any big ocamlformat failures, feel free to add them to the [test](https://github.com/aantron/dream/blob/master/test/ocamlformat/test.ml), even if there is no way to fix them. Maybe we can get them looked at in the ocamlformat repo.

There are still a couple things I would like, such as

```ocaml
let foo = [
  a;
  b;
]
```

instead of

```ocaml
let foo =
  [
    a;
    b;
  ]
```

but I don't think there is a way to get them with current ocamlformat.
