### ISSUE TITLE
Add an example with nginx or other reverse proxy

### ISSUE THREAD

**Issue by aantron** [aantron/dream#98]
While Dream is designed to be able to run on the modern Web without a proxy (e.g., it has direct HTTP/2, HTTPS support, etc.), in practice, depending on deployment, Dream will still often run behind a proxy. So, we want to make sure Dream and proxies interact well. At least a basic nginx example will help people set up quickly, and will give us an easy way to work out proxy header-reading middleware. See #10. We should probably document whatever comes out of #10 in the nginx example.

Respecting proxy headers such as `X-Forwarded-Proto` (#10) is actually a security issue (in terms of defense in depth, rather than actual vulnerabilities), since we need to know if nginx served as an HTTPS endpoint (even if Dream gets a non-HTTPS connection from nginx) to, for instance, have Dream automatically choose more secure cookie settings that require knowing that we are running under HTTPS.

cc @thangngoc89

**Comment by thangngoc89** [comment]
I would really love to help but I don’t know nginx actually. It’s auto configured for me by dokku 😭

**Comment by aantron** [comment]
Done by @jsthomas in #140.

This makes it much easier to address #10 for at least nginx.
